### ISSUE TITLE
Roadmap v0.1

### ISSUE THREAD

**Issue by valkyrienyanko** [Valks-Games/valks-game#2]
### Environment
- [x] Icosahedron (triangles)
- [ ] Icosahedron (hexagons)
- [ ] Planet Chunk Rendering
- [ ] Solar Systems
- [ ] Top down view map of solar system
- [ ] 3D Map of Space Sectors
- [ ] Fog of War on planet surface?

### Camera
- [x] Mouse scroll zoom movement when locked onto planet
- [ ] Smooth lerp movement on zoom and drag when locked onto planet
- [ ] Unlock from planet view to space view

### Units
- [x] RTS Selection
- [x] Spherical RigidBody Movement
- [x] Spherical Position Movement
- [ ] Task: Move to Target
- [ ] Task: Harvest Target
- [ ] Task: Gather Resources (Combination of above 2 tasks automated)
- [ ] Task: Defend Target
- [ ] Task: Attack Target
- [ ] Task: Patrol Waypoints

### Msc
- [ ] Models + Animations
